### PR TITLE
Separate Discrete from Continuous models

### PR DESCRIPTION
**Pull request by soypat**
First of all: I am sorry about the last PR I did. I am quite embarrassed of the error I introduced. 

I've changed interface names `Model`-> `DModel`, `Propagator`-> `DPropagator` to indicate they are discrete-time functions and that they are not compatible with `sim.Continuous` implementation. Let me know if any of the changes are too much.

### CODE REVIEW

**Comment by milosgajdos** [comment]
I need to think about this a bit. I'm not a massive fan of `DModel` and `DPropagate` nomenclature. Also, I wonder if we should revert the previous commit/release 🤔

**Comment by soypat** [comment]
If it's not too much of a hassle reverting would be good since I really botched it up

**Comment by soypat** [comment]
@milosgajdos Alright, so plenty of changes to API's. I may have overstepped the line but I am finding it hard to consolidate old `Model`/`DiscreteModel`. 

The reason their names were switched is because old `Model` was actually a discrete-time model. `DiscreteModel` just added the modern control theory Matrices on top of that.

**Comment by soypat** [comment]
Now I'm thinking of another naming scheme:
`DiscreteControlSystem` maybe implies a lot more than it does. I'd imagine a discrete control system to also have information on Equilibrium positon (set point) for a controller and covariance of sensor measurements- basically a system ready to be controlled by an arbitrary controller. Maybe something along the lines of `DiscreteSystem` would be more faithful to its purpose.

**Comment by soypat** [comment]
@milosgajdos What do you think of the change of name?
> DiscreteControlSystem maybe implies a lot more than it does. I'd imagine a discrete control system to also have information on Equilibrium positon (set point) for a controller and covariance of sensor measurements- basically a system ready to be controlled by an arbitrary controller. Maybe something along the lines of DiscreteSystem would be more faithful to its purpose.

**Comment by soypat** [comment]
Closed due to conflicts. I was a git novice when I PRed this.

**Pull request closed without merging**
