### PR TITLE
fix BaseModel.Propagate() implementation

### PR DESCRIPTION
**Pull request by soypat**
I found a rather serious mistake in the implementation of `Propagate()`.

The issue is that next state was calculated as `X_{n+1} = A*X_{n} + B*U`. The equation modern control theory supposes is `dX/dt = A * X_{n} + B*U` which means you have to integrate the result in time.

### CODE REVIEW

**Comment by soypat** [comment]
Let me know if you want me to fix the examples before merging and releasing an update! I'd be happy to do so

**Comment by milosgajdos** [comment]
Interesting. We've used the original model on a few projects and have not noticed any major discrepancies. I'll have a look at this later on today. Thanks.

**Comment by soypat** [comment]
@milosgajdos I've [pushed changes](https://github.com/milosgajdos/go-estimate-examples/pull/1) on how the application changes to go-estimate-examples. The graphs seem to have changed only superficially given the new falling ball model which leads me to think you used the same backing equations to describe the system.

**Comment by milosgajdos** [comment]
Hm, interesting. Ok, I see no harm in adding this in + it makes sense.

**Review by milosgajdos — APPROVED** [review]

**Comment by milosgajdos** [comment]
This has now been reverted and the release cut as a result of this was deleted too.

**Pull request merged**
